server {
    listen 80;
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    # Archivos estáticos (tu SPA sencilla)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia el backend en la subred privada
    location /api/ {
    # Usamos el nombre del contenedor que creamos antes
    proxy_pass http://back-perritos:3001/; 
    
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    }   
}
